# Generated by Django 4.1.3 on 2022-11-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('banco', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=19)),
                ('fechamento', models.DecimalField(decimal_places=0, max_digits=2)),
                ('vencimento', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
